### ISSUE TITLE
USER STORY: Register for an Account

### ISSUE THREAD

**Issue by vica781** [vica781/The_Literary_Loft#1]
As a ***Site User***, I want to ***easily register for my account***, so that I can ***have a personal account and be able to view my profile***

***

### ACCEPTANCE CRITERIA
_A set of predefined requirements that must be met to meet the user story needs (and mark it as complete)_.

- [ ] User can access a registration page.
- [ ] User can fill out a registration form with necessary details.
- [ ] User receives a confirmation email after successful registration.

***

### TASKS
_A single unit of work broken down from the defined user story_

- [ ] Create a registration form.
- [ ] Implement form validation.
- [ ] Set up email confirmation for new registrations.
