### ISSUE TITLE
USER STORY: Register for an Account

### ISSUE THREAD

**Issue by vica781** [vica781/The_Literary_Loft#11]
**Description:** 
As a Site User, I want to easily register for an account, so that I can have a personal account and be able to view my profile.

**Acceptance Criteria:**
- [x] User can access a registration page.
- [x]  User can fill out a registration form with necessary details.
- [x]  User receives a confirmation email after successful registration.

**Tasks:** 
- [x] Create a registration form.
- [x]  Implement form validation.
- [x]  Set up email confirmation for new registrations.
