### ISSUE TITLE
USER STORY: Register for an Account

### ISSUE THREAD

**Issue by vica781** [vica781/The_Literary_Loft#12]
**Description:** 

- [ ] As a Site User, I want to easily register for an account, so that I can have a personal account and be able to view my profile.

**Acceptance Criteria:**

- [ ]  User can access a registration page.
- [ ]  User can fill out a registration form with necessary details.
- [ ]  User receives a confirmation email after successful registration.

**Tasks:**
 

- [ ] Create a registration form.
- [ ]  Implement form validation.
- [ ]  Set up email confirmation for new registrations.
