### ISSUE TITLE
USER STORY: Login or Logout

### ISSUE THREAD

**Issue by vica781** [vica781/The_Literary_Loft#2]
As a ***Site User***, I want to ***easily login or logout***, so that I can ***access my personal account information***.

***

### ACCEPTANCE CRITERIA
_A set of predefined requirements that must be met to meet the user story needs (and mark it as complete)_.

- [ ] User can access a login page.
- [ ] User can enter credentials to log in.
- [ ] User can easily log out from their account.

***

### TASKS
_A single unit of work broken down from the defined user story_

- [ ] Create a login form.
- [ ] Implement login and logout functionality.
- [ ] Ensure session management for logged-in users.
