### ISSUE TITLE
USER STORY: Edit/Update a Product

### ISSUE THREAD

**Issue by vica781** [vica781/The_Literary_Loft#21]
**Description:** 
As a Store Owner, I want to edit/update a product, so that I can change product prices, descriptions, images, and other product criteria.

**Acceptance** Criteria:
- [x] Admin can access a product editing page.
- [x]  Admin can edit existing product details.
- [x]  Admin can submit the form to update the product information.

**Tasks:**
- [x] Create a product editing form.
- [x]  Implement form validation.
- [x]  Ensure the updated product details are saved in the database.
