### ISSUE TITLE
USER STORY: Recover Password

### ISSUE THREAD

**Issue by vica781** [vica781/The_Literary_Loft#3]
As a ***Site User***, I want to ***easily recover my password in case I forget it***, so that I can ***recover access to my account***.

***

### ACCEPTANCE CRITERIA
_A set of predefined requirements that must be met to meet the user story needs (and mark it as complete)_.

- [ ] User can request password recovery.
- [ ] User receives a password recovery email.
- [ ] User can reset their password using the link provided.

***

### TASKS
_A single unit of work broken down from the defined user story_

- [ ] Create a password recovery form.
- [ ] Set up email functionality for password recovery.
- [ ] Implement password reset functionality.
