### ISSUE TITLE
USER STORY: Edit/Update a Product

### ISSUE THREAD

**Issue by vica781** [vica781/The_Literary_Loft#6]
As a ***Store Owner***, I want to ***edit/update a product***, so that I can ***change product prices, descriptions, images, and other product criteria***.

***

### ACCEPTANCE CRITERIA
_A set of predefined requirements that must be met to meet the user story needs (and mark it as complete)_.

- [x] Admin can access a product editing page.
- [x] Admin can edit existing product details.
- [x] Admin can submit the form to update the product information.
***

### TASKS
_A single unit of work broken down from the defined user story_

- [x] Create a product editing form.
- [x] Implement form validation.
- [x] Ensure the updated product details are saved in the database.
