### ISSUE TITLE
USER STORY: Delete a Product

### ISSUE THREAD

**Issue by vica781** [vica781/The_Literary_Loft#7]
As a ***Store Owner***, I want to ***delete a product***, so that I can ***remove items that are no longer for sale***.

***

### ACCEPTANCE CRITERIA
_A set of predefined requirements that must be met to meet the user story needs (and mark it as complete)_.

- [x] Admin can access a list of products.
- [x] Admin can select a product to delete.
- [x] Admin receives a confirmation prompt before deletion.
- [x] The product is removed from the store upon confirmation.

***

### TASKS
_A single unit of work broken down from the defined user story_

- [x] Create a product deletion interface.
- [x] Implement a confirmation prompt for deletions.
- [x] Ensure the product is removed from the database and the store.
